config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/hello'
  root to: "welcome#hello"

  resources :users, only: [:show] do
    resources :items, only: [:create, :destroy, :edit, :update]
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
  def after_sign_in_path_for(resource)
        return user_path(resource)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    @item = Item.new(params[:item].permit!)
    @item.user = current_user
    @item.save
    redirect_to :back
  end

  def destroy
    @item = Item.find(params[:id])
    @item.delete
    redirect_to "/users/#{current_user.id}"
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    #Which Item are we supoosed to be updating here?
    @item = Item.find(params[:id])
    @item.name = params[:item][:name]
    @item.save
    redirect_to current_user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def hello
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [current_user, item] do |f| %>
   <div class="form-group">
     <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: "Enter to-do item name" %>
   </div>

   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>

app/views/items/_item.html.erb
<li> <b> <%= item.name %> </b> <br> <small> (<%= distance_of_time_in_words(item.created_at, Time.now) %>)</small> </li>
<%= link_to "Edit", edit_user_item_path(current_user, item), class: 'glyphicon glyphicon-edit' %> <br>
<%= link_to "Mark as complete", [current_user, item], method: :delete, class: 'glyphicon glyphicon-check' %>

app/views/items/create.html.erb
new create view!!!

app/views/items/edit.html.erb
<h1>Edit item</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([current_user, @item]) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

 <div class="row">

   <div class="col-md-4">
     <p>Create a new to-do item</p>
   </div>

   <div class="col-md-8">
     <%= render partial: 'form', locals: { item: @item } %>
   </div>
 </div>

app/views/items/show.html.erb
<%= render partial: 'form', locals: { item: @item } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  | <%= link_to "Sign Up", new_user_registration_path %> |
  <%= link_to "Sign In", new_user_session_path %> |
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> |

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class='container'>
    <%= yield %>
  </div>

</body>
</html>

app/views/users/show.html.erb
<b> <font color="green"> User email: <%= @user.email %> <br>
User since: <%= @user.created_at %> <br>
Last sign in: <%= @user.last_sign_in_at %> <br></font></b>
<h2>Items</h2>

<ol>
<%= render @user.items %>
</ol>



<%= render partial: "/items/form", locals: {item: @user.items.new } %>

app/views/welcome/hello.html.erb
<div class="row">
  <div class="col-md-4 red bold four-em-height">
    left side
  </div>
  <div class="col-md-5 yellow italic fantasy bold textcenter four-em-height">
    <h1>Welcome#hello</h1>
  </div>
  <div class="col-md-3 red bold four-em-height">
    right side
  </div>
</div>
<div class="row">
  <div class="col-md-11 blue three-em-height">
  </div>
  <div class="col-md-1 blue three-em-height">
<p>line up to the right</p>
  </div>
</div>